#!/bin/bash

set -e

pushd "$(dirname $0)" > /dev/null

IMAGE_TAG=${IMAGE_TAG:-"latest"}
K8S_PROJECT=${K8S_PROJECT:-"display-pattern-lab"}
BRANCH_NAME=${BRANCH_NAME:-"master"}

./build-and-push-dev-image
./install

cp -R ../output images/prod/
docker build -t dr.chefkoch.net/$K8S_PROJECT images/prod

if [ "${IMAGE_TAG}" != "latest" ]
then
    docker tag -f dr.chefkoch.net/$K8S_PROJECT:latest dr.chefkoch.net/$K8S_PROJECT:$IMAGE_TAG
fi

rm -rf images/prod/output

if [ "${BRANCH_NAME}" == "master" ]
then
    docker push dr.chefkoch.net/$K8S_PROJECT:latest
fi

docker push dr.chefkoch.net/$K8S_PROJECT:$IMAGE_TAG
